dateModified: 1555355672
email:
  fromEmail: $SYSTEM_EMAIL_ADDRESS
  fromName: $SYSTEM_EMAIL_NAME
  template: null
  transportType: craft\mail\transportadapters\Sendmail
  transportSettings: null
fieldGroups:
  95a08367-fb87-4b1a-b522-7d495b0ff6f9:
    name: Common
siteGroups:
  320dbaef-a3c8-41d0-9ef6-f50b94891b6e:
    name: Default
sites:
  19bcec29-0fe8-40ec-ab48-7caaaff62a9a:
    siteGroup: 320dbaef-a3c8-41d0-9ef6-f50b94891b6e
    name: 'REPLACE ME'
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: 'http://$DEFAULT_SITE_URL'
    sortOrder: 1
    primary: true
system:
  edition: solo
  name: $SYSTEM_NAME
  live: true
  schemaVersion: 3.1.26
  timeZone: America/New_York
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
